name: fwi_ls

channels:
  - conda-forge
  - defaults
  - haasad

dependencies:
  - python==3.8
  - matplotlib==3.1.3
  - numpy==1.18.5
  - scipy==1.4.1
  - pytest==5.4.2
  - pybind11==2.4.3
  - eigen==3.3.7
  - pandas==1.0.3
  - pypardiso==0.2.2
  - pytest-regressions==2.0.1
  - invoke==1.3.0
  - joblib==0.16.0

